#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from deeptools.correctGCBias import main
import numpy as np

if __name__ == '__main__':
    np.random.seed(2025)
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())